template:
  type: file
  path: fargate-service.yaml.j2
stack_name: pad-eschol-api-prd
parameters:
  Cpu: 2048
  Memory: 16384
  Dbuser: escholdba
  Escholurl: 'https://escholarship.org'
  Submitserver: 'pub-submit3-prd.escholarship.org'
sceptre_user_data:
  environment: prd
